name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Run checks
        run: nix flake check

      - name: Check formatting
        run: nix run nixpkgs#nixpkgs-fmt -- . --check
