name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Run checks
        run: nix flake check

      - name: Check formatting
        run: nix run nixpkgs#nixpkgs-fmt -- . --check
