name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4

      - name: Run checks
        run: nix flake check

      - name: Check formatting
        run: nix run nixpkgs#nixpkgs-fmt -- . --check
